### ISSUE TITLE
Buttons for resizing layers

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#15]
- Give all selected layers the same x1 and x2 values using the largest layer as a guide
- Give all selected layers the same x1 and x2 values using the smallest layer as a guide
- Give all selected layers the same y1 and y2 values using the largest layer as a guide
- Give all selected layers the same y1 and y2 values using the smallest layer as a guide

**Comment by Mxchaeltrxn** [comment]
I understand this but I can't think of what each button label should be or look like (if it's an icon). As for its position, I imagine it'd be below the current resize section buttons

**Comment by haydn** [comment]
@Mxchaeltrxn We could call them something like: "Fit Widest", "Fit Narrowest", "Fit Tallest" and "Fit Shortest" for now, but yeah… ultimately icons would be better. (That can be done as part of #48.) Under those other resize buttons sounds good. :+1:
