### ISSUE TITLE
Add validate() function to component definitions

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#34]
The function will have two uses:

1.  To validate the values a designer has entered in via the option panel (e.g. limit the number of characters allowed in a string option).
2.  To validate a saved file (could be used in a CI step to ensure no-one accidentally corrupts a design file or to check if a dependency update has borked a file).

It should return a list of error messages if there's something wrong as well as the key of the option the messages is about:

```js
validate: options => {
  if (options.text.length > 100) {
    return [{ key: "text", message: "Must be less than 100 characters long" }];
  }
  return []; // Maybe this should return null or undefined if everything is fine?
}
```

**Comment by Mxchaeltrxn** [comment]
I can take this one on.

Some questions though:
1. The character length should differ depending on whether it's a long-string or short-string, right?
2. I don't really understand saved file validation because I don't know how saving works in this app

**Comment by haydn** [comment]
@Mxchaeltrxn Thanks!

Hmm… I probably need to explain things a bit better.

The idea is that a developer who installs Sketchbook can customise the `config.js` file to make their own components available to a designer who uses it. The components they add could have specific requirements about the props they can receive. For example, a component that displays a YouTube video might require a video ID to be provided or a credit card input might require a 16 digit card number. The `validate()` function we’re adding will give the developer an opportunity to impose these constraints and provide a feedback to the designer if they enter something that is invalid (through the error messages it return that can be displayed in the options panel).

So, in answer to your question:

> The character length should differ depending on whether it's a long-string or short-string, right?

No. It should be possible for any validation of the options to be done using the `validate()` function. The length of the string is just one example and it could be applied to `short-string`, `long-strong` or any other input types.

> I don't really understand saved file validation because I don't know how saving works in this app

Right! I haven’t explained this anywhere! 😄 It’s just in my head at the moment.

Eventually, designers will be able to save a design they’re working on. That will be saved as a JSON file somewhere (it’ll pretty much be a dump of what we store in `state.doc`). The problem that arises is that the developer can change the `config.js` file and break existing files a designer has saved (because the developer changed the underlying component or something like that). To help mitigate this problem we can provide a script they can automatically run to check if all the saved files are compatible with the current config and part of that script will run `validate()` on the options for each component to see if they’re okay. I wouldn’t worry too much about this, because if the `validate()` function works for the first case, it should work for this one too.
