### ISSUE TITLE
Prevent default behaviour for keys we're using

### ISSUE THREAD

**Issue by Mxchaeltrxn** [haydn/sketchbook-js#39]
# Objective

Prevent the default browser behaviour that occurs when various keys we're using of other purposes are pressed. Including, but not limited to:

- Using shift + right arrow key is highlighting text as well as moving component 10 pixels at a time
- Some browsers (like Firefox) use the backspace to navigate back in history.
- Theoretically, hitting the space key will be trying to scroll down the page (just happens to not be causing any issues because the page is 100% of the viewport's height).

# Rationale

We want to mimic the editing experience a designer would have in a native app like Sketch, Figma, Adobe XD or Illustrator. That means we're going to have to work against some of the natural web affordances to make it feel more native. At some point in the future it might even make sense for the editor to be wrapped up into a standalone app using [Electron](https://www.electronjs.org/).

# Notes

- From some quick googling, it seems like backspace is handled differently across browsers and preventing default behaviour might be a bit tricky because we still want users to be able to delete text when typing into an input.

**Comment by haydn** [comment]
Oh! Hmm… be good to investigate ways to prevent this. I suspect `preventDefault()` will be the solution, but there might be better options I’m not aware of.

**Comment by haydn** [comment]
@Mxchaeltrxn I'm going to rework this issue to incorporate the backspace problem you mentioned (https://github.com/haydn/sketchbook/pull/35#issuecomment-576898442) and to also fix-up any other cases where we want to prevent the default key behaviour.
