### ISSUE TITLE
Resize handles are incorrectly shown even when nothing it selected

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#54]
If nothing is selected you can the drag handles appearing in the top-left corner:

![image](https://user-images.githubusercontent.com/27211/73585944-c07aaf80-44fa-11ea-84a6-00c35b3535f4.png)

If you hover the mouse of the 0,0 point you'll also get a resize cursor.

The drag handles should not be rendered and the cursor shouldn't be modified if `selection.size === 0`.

**Comment by Mxchaeltrxn** [comment]
I can do this
