### ISSUE TITLE
Drag and drop layers to reorder

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#6]

**Comment by Mxchaeltrxn** [comment]
I have found a way to implement this easily without a package if we are moving one layer at a time. If we are moving multiple layers, I'm not sure if there's an easy way to do it. I'll have to do some more research. 

Do you think we should use a package for this like react-dnd or implement it ourselves?

**Comment by haydn** [comment]
@Mxchaeltrxn Yeah, drag-and-drop is always a pain. I've used react-beautiful-dnd in the past: 

https://github.com/atlassian/react-beautiful-dnd

It's got multi-drag support out of the box:

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/multi-drag.md

I think we need multi-drag because otherwise it's going to be ugly handling the case where a user has multiple layers selected.
